<?php
require_once 'includes/functions.php';
$start = microtime(true);
$health = get_detailed_health();
$latency = (int)round((microtime(true) - $start) * 1000);
$online = ($health['status'] ?? '') === 'healthy' || !empty($health['ok']);
$bot = is_array($health['bot'] ?? null) ? $health['bot'] : [];
$metrics = is_array($health['metrics'] ?? null) ? $health['metrics'] : [];
$uptime = (int)($health['uptime_seconds'] ?? 0);
$uptimeText = $uptime > 0 ? floor($uptime/86400).'d '.floor(($uptime%86400)/3600).'h' : 'Unavailable';
$avatar = is_logged_in() ? user_avatar_url() : '';
?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Status — Rallybit</title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet"><link rel="stylesheet" href="/dashboard/style.css?v=6.2"><link rel="icon" href="/favicon.ico" sizes="any"><link rel="icon" type="image/png" sizes="32x32" href="/assets/brand/rallybit-icon-32.png"><link rel="icon" type="image/png" sizes="192x192" href="/assets/brand/rallybit-icon-192.png"><link rel="apple-touch-icon" href="/assets/brand/apple-touch-icon.png"></head><body><div class="dash-shell"><?php render_dashboard_sidebar('status'); ?><main class="dash-main"><header class="dash-header"><div><span class="kicker">Live service health</span><h1>System status</h1><p>A direct view of the bot engine and dashboard bridge.</p></div><span class="status-pill"><span class="dot <?=$online?'online':''?>"></span><?=$online?'All systems operational':'Service interruption'?></span></header><section class="status-grid"><article class="status-card"><h3>Bot engine</h3><strong><?=$online?'Online':'Offline'?></strong><p><?=htmlspecialchars((string)($health['engine'] ?? 'Rallybit API'))?></p></article><article class="status-card"><h3>API response</h3><strong><?=$latency?> ms</strong><p>Measured from this dashboard request.</p></article><article class="status-card"><h3>Uptime</h3><strong><?=$uptimeText?></strong><p>Time since the current bot process started.</p></article><article class="status-card"><h3>Connected servers</h3><strong><?=number_format((int)($bot['guilds'] ?? 0))?></strong><p>Communities currently visible to Rallybit.</p></article><article class="status-card"><h3>Reach</h3><strong><?=number_format((int)($bot['users'] ?? 0))?></strong><p>Combined member count across connected servers.</p></article><article class="status-card"><h3>Runtime load</h3><strong><?=htmlspecialchars((string)($metrics['memory_percent'] ?? '—'))?>%</strong><p>Memory usage reported by the bot host.</p></article></section></main></div></body></html>
